default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
	url: <%= ENV["DATABASE_URL"] {"postgres://localhost:5433/#{Rails.env}" } %>
  
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
